# Generated by Django 3.0.6 on 2020-12-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newpage',
            new_name='newspage',
        ),
    ]
