# Generated by Django 3.0.6 on 2020-12-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('ad_class', models.CharField(choices=[('10th', '10th'), ('9th', '9th'), ('8th', '8th'), ('7th', '7th'), ('6th', '6th')], max_length=5)),
                ('DOB', models.DateField()),
                ('place_birth', models.CharField(max_length=50)),
                ('nation', models.CharField(choices=[('in', 'India'), ('pk', 'Pakistan'), ('sl', 'Srilanka'), ('ch', 'Chain'), ('us', 'Us')], max_length=10)),
                ('state', models.CharField(choices=[('OD', 'Odisha'), ('AP', 'Andhrapradesh'), ('TS', 'Telengana'), ('CG', 'Chhattisgarh'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('BR', 'Bihar'), ('GA', 'Goa')], max_length=20)),
                ('religion', models.CharField(choices=[('hindu', 'Hindu'), ('musilim', 'musilim'), ('sikh', 'sikh'), ('christian', 'christian')], max_length=12)),
                ('gender', models.BooleanField(choices=[('m', 'male'), ('f', 'female')])),
            ],
        ),
    ]
