# Generated by Django 3.0.6 on 2020-12-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_auto_20201215_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='blood_group',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='registermodel',
            name='caste',
            field=models.CharField(choices=[('obc', 'OBC'), ('sc', 'SC'), ('st', 'ST'), ('general', 'General')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registermodel',
            name='identification_mark',
            field=models.CharField(max_length=65, null=True),
        ),
        migrations.AddField(
            model_name='registermodel',
            name='other_info',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='registermodel',
            name='permanent_address',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='registermodel',
            name='pin_code',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
